version: '3'

services:
  angular:
    build: front-end/.
    volumes:
      - .:/usr/front-end/src/app
      - /usr/front-end/src/app/node_modules
    ports:
      - 8080:4200
    command: npm run prod
  express:
    environment:
      - MONGO_URI=${MONGO_URI}
    build: server/.
    volumes:
      - .:/usr/server
      - /usr/server/node_modules
    ports:
      - 3000:3000
    command: npm start
